// src/components/RegistrationForm.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { User, Mail, Lock, Eye, EyeOff, ChevronRight, Loader2, AlertCircle, CheckCircle2 } from 'lucide-vue-next'
import { 
  validateName, validateEmail, validatePassword, getPasswordStrength, type Role 
} from '../utils/validation'

const emit = defineEmits<{
  (e: 'success', email: string): void
  (e: 'switch-to-login'): void
}>()

const formData = ref({
  name: '',
  email: '',
  role: 'user' as Role,
  password: '',
  confirmPassword: ''
})

const showPassword = ref(false)
const showConfirmPassword = ref(false)
const isLoading = ref(false)
const errors = ref<Record<string, string>>({})
const successMsg = ref<string | null>(null)

const passwordStrength = computed(() => getPasswordStrength(formData.value.password))

const strengthColor = computed(() => {
  const strength = passwordStrength.value
  if (strength <= 25) return "bg-red-500"
  if (strength <= 75) return "bg-yellow-400"
  return "bg-green-500"
})

const validateForm = () => {
  const newErrors: Record<string, string> = {}
  const nameV = validateName(formData.value.name)
  if (!nameV.isValid) newErrors.name = nameV.message!
  const emailV = validateEmail(formData.value.email)
  if (!emailV.isValid) newErrors.email = emailV.message!
  const passV = validatePassword(formData.value.password)
  if (!passV.isValid) newErrors.password = passV.message!
  if (formData.value.password !== formData.value.confirmPassword) newErrors.confirmPassword = "Passwords do not match"
  errors.value = newErrors
  return Object.keys(newErrors).length === 0
}

const handleSubmit = async () => {
  if (!validateForm()) return
  isLoading.value = true
  
  setTimeout(() => {
    isLoading.value = false
    let msg = "Registration successful! Flipping to login..."
    if (formData.value.role === 'reviewer') {
      msg = "Your reviewer registration has been submitted and is pending admin approval. Flipping to login..."
    }
    successMsg.value = msg
    
    setTimeout(() => {
      emit('success', formData.value.email)
    }, 2000)
  }, 1500)
}
</script>

<template>
  <div class="w-full h-full flex flex-col justify-center p-8 md:p-12 overflow-y-auto custom-scrollbar">
    <div class="max-w-md mx-auto w-full py-8">
      <header class="mb-8">
        <h2 class="text-3xl font-bold text-black mb-2">Create Account</h2>
        <p class="text-zinc-500 text-sm">Join the Kerala Mathematical Association</p>
      </header>

      <Transition name="fade-scale" mode="out-in">
        <div v-if="successMsg" class="p-8 bg-zinc-50 border border-zinc-200 rounded-3xl flex flex-col items-center text-center space-y-4">
          <div class="w-20 h-20 bg-black text-white rounded-full flex items-center justify-center shadow-2xl shadow-black/20">
            <CheckCircle2 :size="40" />
          </div>
          <div class="space-y-2">
            <p class="text-black font-bold text-lg">Registration Success</p>
            <p class="text-zinc-600 text-sm leading-relaxed">{{ successMsg }}</p>
          </div>
          <div class="pt-4 flex gap-2">
            <div class="w-2 h-2 bg-black rounded-full animate-bounce"></div>
            <div class="w-2 h-2 bg-black rounded-full animate-bounce delay-200"></div>
            <div class="w-2 h-2 bg-black rounded-full animate-bounce delay-400"></div>
          </div>
        </div>

        <form v-else @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Name -->
          <div class="space-y-2">
            <label class="form-label" for="reg-name-vue">Full Name</label>
            <div class="relative group">
              <User class="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-black transition-colors" :size="18" />
              <input
                id="reg-name-vue"
                v-model="formData.name"
                class="input-field pl-12"
                :class="{ 'border-red-500': errors.name }"
                placeholder="Enter your full name"
              />
            </div>
            <p v-if="errors.name" class="text-red-500 text-[11px] font-medium flex items-center gap-1 ml-1"><AlertCircle :size="10"/> {{ errors.name }}</p>
          </div>

          <!-- Email -->
          <div class="space-y-2">
            <label class="form-label" for="reg-email-vue">Email Address</label>
            <div class="relative">
              <Mail class="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" :size="18" />
              <input
                id="reg-email-vue"
                v-model="formData.email"
                type="email"
                class="input-field pl-12"
                :class="{ 'border-red-500': errors.email }"
                placeholder="Enter your email address"
              />
            </div>
            <p v-if="errors.email" class="text-red-500 text-[11px] font-medium flex items-center gap-1 ml-1"><AlertCircle :size="10"/> {{ errors.email }}</p>
          </div>

          <!-- Role -->
          <div class="space-y-3">
            <label class="form-label">Role Selection</label>
            <div class="grid grid-cols-3 gap-2">
              <button
                v-for="r in (['user', 'author', 'reviewer'] as Role[])"
                :key="r"
                type="button"
                @click="formData.role = r"
                class="py-3 rounded-xl border transition-all text-[10px] font-bold uppercase tracking-widest"
                :class="formData.role === r ? 'bg-black text-white border-black shadow-lg shadow-black/20' : 'bg-white text-zinc-400 border-zinc-200 hover:border-black/30'"
              >
                {{ r }}
              </button>
            </div>
          </div>

          <!-- Password -->
          <div class="space-y-2">
            <label class="form-label" for="reg-password-vue">Password</label>
            <div class="relative">
              <Lock class="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" :size="18" />
              <input
                id="reg-password-vue"
                v-model="formData.password"
                :type="showPassword ? 'text' : 'password'"
                class="input-field pl-12 pr-12"
                :class="{ 'border-red-500': errors.password }"
                placeholder="••••••••"
              />
              <button
                type="button"
                @click="showPassword = !showPassword"
                class="absolute right-4 top-1/2 -translate-y-1/2 text-zinc-400"
              >
                <EyeOff v-if="showPassword" :size="18" />
                <Eye v-else :size="18" />
              </button>
            </div>
            <!-- Strength -->
            <div class="flex gap-1.5 mt-2">
              <div 
                v-for="i in [1, 2, 3, 4]" :key="i"
                class="h-1 px-1 flex-1 rounded-full transition-all duration-700"
                :class="passwordStrength >= i * 25 ? strengthColor : 'bg-zinc-100'"
              ></div>
            </div>
          </div>

          <!-- Confirm Password -->
          <div class="space-y-2">
            <label class="form-label" for="reg-confirm-vue">Confirm Password</label>
            <div class="relative">
              <Lock class="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" :size="18" />
              <input
                id="reg-confirm-vue"
                v-model="formData.confirmPassword"
                :type="showConfirmPassword ? 'text' : 'password'"
                class="input-field pl-12 pr-12"
                :class="{ 'border-red-500': errors.confirmPassword }"
                placeholder="••••••••"
              />
              <button
                type="button"
                @click="showConfirmPassword = !showConfirmPassword"
                class="absolute right-4 top-1/2 -translate-y-1/2 text-zinc-400"
              >
                <EyeOff v-if="showConfirmPassword" :size="18" />
                <Eye v-else :size="18" />
              </button>
            </div>
          </div>

          <button 
            type="submit" 
            :disabled="isLoading"
            class="btn-primary w-full flex items-center justify-center gap-2 group mt-4 overflow-hidden"
          >
            <Loader2 v-if="isLoading" class="animate-spin" :size="20" />
            <template v-else>
              <span class="relative z-10">Register</span>
              <ChevronRight :size="18" class="relative z-10 transition-transform group-hover:translate-x-1" />
            </template>
          </button>

          <p class="text-center text-zinc-500 text-sm">
            Already have an account?
            <button 
              type="button"
              @click="emit('switch-to-login')"
              class="text-black font-bold hover:underline ml-1"
            >
              Login
            </button>
          </p>
        </form>
      </Transition>
    </div>
  </div>
</template>

<style scoped>
.fade-scale-enter-active, .fade-scale-leave-active { transition: all 0.3s ease; }
.fade-scale-enter-from, .fade-scale-leave-to { opacity: 0; transform: scale(0.95); }

.delay-200 { animation-delay: 200ms; }
.delay-400 { animation-delay: 400ms; }
</style>

// frontend/src/components/RegistrationForm.tsx
import React, { useState } from 'react';
import { User, Mail, Lock, Eye, EyeOff, ChevronRight, Loader2, CheckCircle2, GraduationCap, Briefcase, AlertCircle } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '../utils/cn';
import {
  validateName,
  validateEmail,
  type Role
} from '../utils/validation';
import { register } from '../services/auth.service';

interface RegistrationFormProps {
  onSuccess: (email: string) => void;
  onSwitchToLogin: () => void;
}

const RegistrationForm: React.FC<RegistrationFormProps> = ({ onSuccess, onSwitchToLogin }) => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    role: 'user' as Role,
    password: '',
    confirmPassword: '',
    qualification: '',
    experience: ''
  });

  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  const passwordsMatch =
    formData.password.length > 0 &&
    formData.confirmPassword.length > 0 &&
    formData.password === formData.confirmPassword;

  const isFormReady = 
    formData.name.length > 0 && 
    formData.email.length > 0 && 
    formData.password.length === 8 && 
    passwordsMatch &&
    (formData.role !== 'reviewer' || (formData.qualification.length > 0 && formData.experience.length > 0));

  const validateForm = () => {
    const newErrors: Record<string, string> = {};
    const nameV = validateName(formData.name);
    if (!nameV.isValid) newErrors.name = nameV.message!;
    const emailV = validateEmail(formData.email);
    if (!emailV.isValid) newErrors.email = emailV.message!;
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0 && isFormReady;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;
    setIsLoading(true);
    setErrors({});

    try {
      await register({
        email: formData.email,
        password: formData.password,
        name: formData.name,
        role: formData.role
      });
      
      let msg = "Registration successful! Flipping to login...";
      if (formData.role === 'reviewer') {
        msg = "Your account is under admin approval. You can log in after approval.";
      }
      setSuccessMsg(msg);

      setTimeout(() => {
        onSuccess(formData.email);
      }, 2000);
    } catch (err: any) {
      setErrors({ form: err.message || 'Registration failed' });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="w-full h-full flex flex-col justify-center p-6 sm:p-8 lg:p-12 overflow-y-auto custom-scrollbar bg-white">
      <div className="max-w-md mx-auto w-full py-4 sm:py-6 lg:py-8">
        {/* Header */}
        <header className="mb-6 sm:mb-8">
          <h2 className="text-2xl sm:text-3xl font-bold text-black mb-1.5 font-['Outfit']">Create Account</h2>
          <p className="text-zinc-500 text-sm">Join the Kerala Mathematical Association</p>
        </header>

        <AnimatePresence mode="wait">
          {successMsg ? (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="p-6 sm:p-8 bg-zinc-50 border border-zinc-200 rounded-2xl flex flex-col items-center text-center space-y-4"
            >
              <div className="w-16 h-16 bg-black text-white rounded-full flex items-center justify-center shadow-2xl shadow-black/20">
                <CheckCircle2 size={36} />
              </div>
              <div className="space-y-2">
                <p className="text-black font-bold text-lg">Registration Success</p>
                <p className="text-zinc-600 text-sm leading-relaxed">{successMsg}</p>
              </div>
            </motion.div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-5">
              {errors.form && (
                <motion.div 
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-4 bg-rose-50 border border-rose-100 rounded-2xl flex items-center gap-3 text-rose-600 shadow-sm"
                >
                  <div className="w-8 h-8 rounded-full bg-rose-100 flex items-center justify-center shrink-0">
                    <AlertCircle size={16} />
                  </div>
                  <p className="text-xs font-bold tracking-tight">{errors.form}</p>
                </motion.div>
              )}
              {/* Full Name */}
              <div className="space-y-1.5">
                <label className="form-label" htmlFor="reg-name">Name</label>
                <div className="relative group">
                  <User className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-black transition-colors" size={18} />
                  <input
                    id="reg-name"
                    type="text"
                    className={cn("input-field pl-11 !border-zinc-200 transition-none", errors.name && "!border-red-500")}
                    placeholder="Enter your name"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  />
                </div>
              </div>

              {/* Email Address */}
              <div className="space-y-1.5">
                <label className="form-label" htmlFor="reg-email">Email</label>
                <div className="relative group">
                  <Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-black transition-colors" size={18} />
                  <input
                    id="reg-email"
                    type="email"
                    className={cn("input-field pl-11 !border-zinc-200 transition-none", errors.email && "!border-red-500")}
                    placeholder="Enter your email"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  />
                </div>
              </div>

              {/* Role Selection */}
              <div className="space-y-2">
                <label className="form-label">Role</label>
                <div className="grid grid-cols-3 gap-2">
                  {(['user', 'author', 'reviewer'] as Role[]).map((r) => (
                    <button
                      key={r}
                      type="button"
                      onClick={() => setFormData({ ...formData, role: r })}
                      className={cn(
                        "py-2.5 rounded-xl border transition-all text-[10px] font-bold uppercase tracking-widest",
                        formData.role === r
                          ? "bg-black text-white border-black shadow-lg shadow-black/20"
                          : "bg-white text-zinc-400 border-zinc-200 hover:border-black/30"
                      )}
                    >
                      {r === 'user' ? 'User' : r === 'author' ? 'Author' : 'Reviewer'}
                    </button>
                  ))}
                </div>
              </div>

              {/* Conditional Reviewer Fields */}
              <AnimatePresence>
                {formData.role === 'reviewer' && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    className="space-y-5 overflow-hidden"
                  >
                    <div className="space-y-1.5">
                      <label className="form-label">Academic Qualification</label>
                      <div className="relative group">
                        <GraduationCap className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-black transition-colors" size={18} />
                        <input
                          type="text"
                          className="input-field pl-11 !border-zinc-200"
                          placeholder="e.g. Ph.D. in Mathematics"
                          value={formData.qualification}
                          onChange={(e) => setFormData({ ...formData, qualification: e.target.value })}
                        />
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <label className="form-label">Professional Experience</label>
                      <div className="relative group">
                        <Briefcase className="absolute left-3.5 top-4 text-zinc-400 group-focus-within:text-black transition-colors" size={18} />
                        <textarea
                          className="input-field pl-11 py-3 min-h-[100px] !border-zinc-200 resize-none"
                          placeholder="Briefly describe your research and editorial background..."
                          value={formData.experience}
                          onChange={(e) => setFormData({ ...formData, experience: e.target.value })}
                        />
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Password */}
              <div className="space-y-1.5">
                <label className="form-label" htmlFor="reg-password">Password</label>
                <div className="relative group">
                  <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-black transition-colors" size={18} />
                  <input
                    id="reg-password"
                    type={showPassword ? "text" : "password"}
                    className="input-field pl-11 pr-11 !border-none !ring-0 !bg-zinc-50"
                    placeholder="Enter your password"
                    maxLength={8}
                    value={formData.password}
                    onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3.5 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-600 transition-colors"
                  >
                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                {/* Password Strength Indicator */}
                <div className="flex gap-1.5 mt-2 h-1">
                  {[1, 2, 3, 4].map((i) => {
                    const strength = formData.password.length;
                    let color = "bg-zinc-100";
                    
                    if (strength > 0) {
                      if (i === 1) {
                        if (strength <= 3) color = "bg-red-500";
                        else if (strength <= 5) color = "bg-amber-500";
                        else color = "bg-green-500";
                      } else if (i === 2 && strength >= 4) {
                        if (strength <= 5) color = "bg-amber-500";
                        else color = "bg-green-500";
                      } else if (i === 3 && strength >= 6) {
                        color = "bg-green-500";
                      } else if (i === 4 && strength >= 8) {
                        color = "bg-green-500";
                      }
                    }

                    return (
                      <div 
                        key={i} 
                        className={cn(
                          "flex-1 rounded-full transition-all duration-500",
                          color
                        )} 
                      />
                    );
                  })}
                </div>
              </div>

              {/* Confirm Password */}
              <div className="space-y-1.5">
                <label className="form-label" htmlFor="reg-confirm">Confirm Password</label>
                <div className="relative group">
                  <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-black transition-colors" size={18} />
                  <input
                    id="reg-confirm"
                    type={showConfirmPassword ? "text" : "password"}
                    className="input-field pl-11 pr-11 !border-none !ring-0 !bg-zinc-50"
                    placeholder="Enter your password again"
                    maxLength={8}
                    value={formData.confirmPassword}
                    onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                  />
                  <button
                    type="button"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    className="absolute right-3.5 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-600 transition-colors"
                  >
                    {showConfirmPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                {/* Underline */}
                <div className={cn(
                  "h-0.5 w-full transition-colors duration-300", 
                  formData.confirmPassword.length === 0 
                    ? "bg-zinc-100" 
                    : formData.password === formData.confirmPassword 
                      ? "bg-green-500" 
                      : "bg-red-500"
                )} />
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isLoading}
                className={cn(
                  "btn-primary w-full flex items-center justify-center gap-2 group mt-4",
                  !isFormReady && "opacity-50 cursor-not-allowed grayscale"
                )}
              >
                {isLoading ? (
                  <Loader2 className="animate-spin" size={20} />
                ) : (
                  <>
                    <span>Register</span>
                    <ChevronRight size={18} className="transition-transform group-hover:translate-x-1" />
                  </>
                )}
              </button>

              {/* Login Link */}
              <p className="text-center text-zinc-500 text-sm pt-1">
                Already have an account?{' '}
                <button
                  type="button"
                  onClick={onSwitchToLogin}
                  className="text-black font-bold hover:underline"
                >
                  Login
                </button>
              </p>
            </form>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default RegistrationForm;
